// <auto-generated />
namespace AmbulancePCR.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class saved2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(saved2));
        
        string IMigrationMetadata.Id
        {
            get { return "202111100309262_saved2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
